image: unitedclassifiedsapps/gitlab-ci-android-fastlane

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_BUILD_TOOLS: "29.0.0"
  ANDROID_SDK_TOOLS: "26.1.1"

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

stages:
  - build

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/